### PR TITLE
Introduction to Business recipe

### PR DESCRIPTION
**Pull request by wilkus27**
Issue: https://github.com/openstax/recipes/issues/158

### CODE REVIEW

**Comment by ajluk** [comment]
@wilkus27 Was there no need to add `BakeUnnumneredFigures` direction to the recipe?

**Review by ajluk — COMMENTED** [review]
I have left just one question, otherwise everything looks good!

**Comment by wilkus27** [comment]
@ajluk Thank you for noticing this :relaxed:

**Review by ajluk — APPROVED** [review]

**Comment by lwtchu** [comment]
Book content error - removed from bake_root for now.

**Pull request merged**
